#NOTE: Reload local server when changing stuff here!

# Site settings
company_name: "Murerfirmaet Bjørklund & Eskildsen ApS"
title: "Murerfirmaet Bjørklund & Eskildsen"
email: "jacob@jacobmurer.dk"
phone: "+45 2946 2067"
address_line1: "Lerhøj 20"
address_line2: "2880 Bagsværd"
cvr: "32 45 11 01"
description: > # this means to ignore newlines until "baseurl:"
  Murerentrepriser siden 1964
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jacobmurer.dk" # the base hostname & protocol for your site
twitter_username: #recph
github_username:  #re-cph

# Build settings
markdown: kramdown

sass:
  style: :compressed
  sass_dir: _sass

gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']